<?php

/**
 * Implements hook_form_alter().
 */
function webform_select2_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, 'webform_client_form') === 0) {
    backdrop_add_library('select2', 'select2');
    $form['#attached']['js'][] = array(
      'type' => 'file',
      'scope' => 'footer',
      'weight' => -10,
      'data' => backdrop_get_path('module', 'webform_select2') . '/js/webform_select2.js',
    );
  }
}

